=== pchurzin/masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru" xmlns:j="http://javaops.ru" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://javaops.ru" elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:all>
                <xs:element name="Cities" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="City" type="cityType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Users" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="User" type="userType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Projects" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="Project" type="projectType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Groups" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="Group" type="groupType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
        <xs:key name="userId">
            <xs:selector xpath="j:Users/j:User"/>
            <xs:field xpath="j:fullName"/>
        </xs:key>
        <xs:key name="groupId">
            <xs:selector xpath="j:Groups/j:Group"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="projectId">
            <xs:selector xpath="j:Projects/j:Project" />
            <xs:field xpath="@id" />
        </xs:key>
        <xs:key name="cityId">
            <xs:selector xpath="j:Cities/j:City" />
            <xs:field xpath="@id" />
        </xs:key>
        <xs:keyref name="userCity" refer="j:cityId">
            <xs:selector xpath="j:Users/j:User" />
            <xs:field xpath="@city" />
        </xs:keyref>
        <xs:keyref name="groupUser" refer="j:userId">
            <xs:selector xpath="j:Groups/j:Group/j:Users/j:User" />
            <xs:field xpath="." />
        </xs:keyref>
        <xs:keyref name="projectGroup" refer="j:groupId">
            <xs:selector xpath="j:Projects/j:Project/j:Groups/j:Group" />
            <xs:field xpath="." />
        </xs:keyref>
    </xs:element>

    <xs:complexType name="userType">
        <xs:sequence>
            <xs:element type="xs:string" name="fullName" />
        </xs:sequence>
        <xs:attribute type="flagType" name="flag" use="required" />
        <xs:attribute type="xs:string" name="city" use="required" />
        <xs:attribute type="xs:string" name="email" use="required" />
    </xs:complexType>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active" />
            <xs:enumeration value="deleted" />
            <xs:enumeration value="superuser" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="id" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="projectType">
        <xs:all>
            <xs:element type="xs:string" name="Name" />
            <xs:element type="xs:string" name="Description" />
            <xs:element name="Groups">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Group" maxOccurs="unbounded">
                            <xs:simpleType>
                                <xs:restriction base="xs:string" />
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute type="xs:string" name="id" use="required" />
    </xs:complexType>

    <xs:complexType name="groupType">
        <xs:all>
            <xs:element type="xs:string" name="Name" />
            <xs:element type="xs:string" name="Description" />
            <xs:element name="Users">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="User" maxOccurs="unbounded">
                            <xs:simpleType>
                                <xs:restriction base="xs:string" />
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="type" type="groupTypeType" use="required" />
        <xs:attribute type="xs:string" name="id" use="required" />
    </xs:complexType>

    <xs:simpleType name="groupTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="registering" />
            <xs:enumeration value="current" />
            <xs:enumeration value="finished" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== pchurzin/masterjava/src/test/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <Users>
        <User flag="active" city="kiv" email="gmail@gmail.com">
            <fullName>Full Name</fullName>
        </User>
        <User flag="superuser" city="spb" email="admin@javaops.ru">
            <fullName>Admin</fullName>
        </User>
        <User flag="deleted" city="spb" email="mail@yandex.ru">
            <fullName>Deleted</fullName>
        </User>
        <User flag="active" city="msk" email="pchurzin@pchurzin.ru">
            <fullName>PChurzin</fullName>
        </User>
    </Users>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
        <City id="msk">Москва</City>
    </Cities>
    <Groups>
        <Group type="finished" id="topjava1">
            <Name>Topjava 1 group</Name>
            <Description>Topjava 1 group description</Description>
            <Users>
                <User>Admin</User>
                <User>PChurzin</User>
                <User>Full Name</User>
            </Users>
        </Group>
        <Group type="current" id="topjava2">
            <Name>Topjava 2 group</Name>
            <Description>Topjava 2 group description</Description>
            <Users>
                <User>Admin</User>
                <User>Deleted</User>
            </Users>
        </Group>
        <Group type="registering" id="masterjava3">
            <Name>masterjava 3 group</Name>
            <Description>Masterjava 3 group description</Description>
            <Users>
                <User>Admin</User>
                <User>PChurzin</User>
            </Users>
        </Group>
    </Groups>
    <Projects>
        <Project id="topjava">
            <Name>Topjava project</Name>
            <Description>Topjava project description</Description>
            <Groups>
                <Group>topjava1</Group>
                <Group>topjava2</Group>
            </Groups>
        </Project>
        <Project id="masterjava">
            <Name>Masterjava project</Name>
            <Description>Masterjava project description</Description>
            <Groups>
                <Group>masterjava3</Group>
            </Groups>
        </Project>
    </Projects>
</Payload>
